
name: ReleaseCI

on: [push]

jobs:
  run_automation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependecies
      env:
        PYTHON_VERSION: "3.10"
      run: |
        py_version=$PYTHON_VERSION
        sudo apt install python"$py_version"
        sudo apt-get install -y nodejs

    - name: Verify Version
      run: |
          python --version
          nodejs -v
          npm --version
          aws --version

    - name: Install libraries for robot
      run: |
          pip install -U pip
          pip install -r requirements.txt
          python -m Browser.entry init

    - name: Run Tests
      run: |
           mkdir results
           TYPE=headless BROWSER=chromium robot -d ./results tests/

    - name: Upload logs in Bucket S3 AWS
      if: ${{ always() }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
            git_hash=$(git rev-parse --short "$GITHUB_SHA")
            echo $git_hash
            bucket=bodytest
            aws s3 cp ${PWD}/results s3://"$bucket"/"$git_hash"/ --recursive --region us-east-1
            echo "RESULT_LOG=https://bodytest.s3.amazonaws.com/$git_hash/log.html" >> $GITHUB_ENV

    - name: Tests ✅
      if: ${{ success() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: BodyTest E2E
        message: |
            All BodyTest E2E tests passed, you're good to go!

    - name: Tests 🚨
      if: ${{ failure() }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: BodyTest E2E
        message: |
            There was a problem in the BodyTest E2E tests! Click here to see what went wrong:(${{ env.RESULT_LOG }})